### ISSUE TITLE
[Provider]: Oracle

### ISSUE THREAD

**Issue by mvrozanti** [dalisoft/awesome-storage#8]
https://www.oracle.com/cloud/free/ -> 200 GB

**Comment by dalisoft** [comment]
@mvrozanti Thank you for interest in project. 
i always check most of providers myself and i could say, experience with oracle cloud is bad. 
- i was not able to create acocunt
- most of users has a this issue
- if even able to create, account or vm has suspended without notify

so i just not added it or some projects noted as not recommended
